SELECT
    C.CAR_ID,
    C.CAR_TYPE,
    ROUND(C.DAILY_FEE * 30 * (100 - P.DISCOUNT_RATE) / 100) AS FEE
FROM CAR_RENTAL_COMPANY_CAR C
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
  ON C.CAR_TYPE = P.CAR_TYPE
 AND P.DURATION_TYPE = '30일 이상'
WHERE C.CAR_TYPE IN ('세단', 'SUV')
  AND C.CAR_ID NOT IN (
      SELECT CAR_ID
      FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
      WHERE END_DATE >= '2022-11-01'
        AND START_DATE <  '2022-12-01'   -- 보통은 12/01은 "미포함"으로 처리
  )
  AND (C.DAILY_FEE * 30 * (100 - P.DISCOUNT_RATE) / 100) >= 500000
  AND (C.DAILY_FEE * 30 * (100 - P.DISCOUNT_RATE) / 100) < 2000000
ORDER BY FEE DESC, C.CAR_TYPE ASC, C.CAR_ID DESC;
